NUM_GPUS: 1
DATALOADER:
  BATCH_SIZE: 1
  NUM_WORKERS: 0
TRAIN:
  ENABLE: False
TEST:
  ENABLE: True
  TEST_CHECKPOINT_PATH: './checkpoints/Xception_FFDF_c23.pth'
DATASET:
  DATASET_NAME: FFDF
  ROOT_DIR: /mldata/FF-DF_test/faces
  TEST_INFO_TXT: /mldata/FF-DF_test/faces/images_crop.txt
  IMG_SIZE: 299
  TRAIN_AUGMENTATIONS:
    COMPOSE:
      [
        Resize,
        HorizontalFlip,
        Normalize
      ]
    NORMALIZE_PARAMS: [[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]]
  TEST_AUGMENTATIONS:
    COMPOSE: [Resize, Normalize]
    NORMALIZE_PARAMS: [[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]]
MODEL:
  MODEL_NAME: Xception
  PRETRAINED: 'imagenet'
  ESCAPE: ''
OPTIMIZER:
  OPTIMIZER_METHOD: adam
  BASE_LR: 0.0002
  ADAM_BETAS: [0.9, 0.999]
  EPS: 0.00000001
  WEIGHT_DECAY: 0.000001
SCHEDULER:
  SCHEDULER_TYPE: step
  DECAY_EPOCHS: 5
  DECAY_RATE: 0.5